services:
  db:
    image: postgres:17-alpine
    container_name: dyn_payment
    shm_size: 128mb
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dyn_payment
      MAX_CONNECTIONS: 1000
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network
    volumes:
      - dyn_payment_pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:8.2-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dyn_payment_pg_data:
